// ── Bulgarian labels for the 3D anatomy UI ──────────────────────────────────
// Reviewed Bulgarian anatomical terms for the 3D viewer.
//
// Covers the strings a user actually SEES: every model label, every topic label
// (the UI chips) and every group name (the click-to-name / isolate targets)
// across all models in lib/anatomy-catalog.ts. Deep leaf-mesh names are NOT
// covered — that is a separate, much larger job.
//
// Keys are the EXACT English/Latin source strings from anatomy-catalog.ts.
// To correct a translation, edit the value only — never the key.
//
// 251 entries.

export const ANATOMY_BG_LABELS: Record<string, string> = {
  'Adrenal glands': 'Надбъбречни жлези',
  'Adrenal glands — everything': 'Надбъбречни жлези — всичко',
  'Arm - arteries': 'Ръка - артерии',
  'Arm - bones': 'Ръка - кости',
  'Arm - capsules, ligaments, fasciae': 'Ръка - капсули, връзки, фасции',
  'Arm - cartilages': 'Ръка - хрущяли',
  'Arm - muscles': 'Ръка - мускули',
  'Arm - nerves': 'Ръка - нерви',
  'Arm - synovia, bursae': 'Ръка - синовия, бурси',
  'Arm - veins': 'Ръка - вени',
  'Arm — all structures': 'Ръка — всички структури',
  'Arm — arteries': 'Ръка — артерии',
  'Arm — bones': 'Ръка — кости',
  'Arm — capsules, ligaments, fasciae': 'Ръка — капсули, връзки, фасции',
  'Arm — cartilages': 'Ръка — хрущяли',
  'Arm — muscles': 'Ръка — мускули',
  'Arm — nerves': 'Ръка — нерви',
  'Arm — synovia, bursae': 'Ръка — синовия, бурси',
  'Arm — veins': 'Ръка — вени',
  'Arteries': 'Артерии',
  'Articular system': 'Ставен апарат',
  'Back - bones': 'Гръб - кости',
  'Back - cartilages': 'Гръб - хрущяли',
  'Back — all structures': 'Гръб — всички структури',
  'Back — bones': 'Гръб — кости',
  'Back — cartilages': 'Гръб — хрущяли',
  'Bones': 'Кости',
  'Bones and cartilages': 'Кости и хрущяли',
  'Bones_right': 'Кости_дясно',
  'Brain': 'Мозък',
  'Brain — everything': 'Мозък — всичко',
  'Bursae': 'Бурси',
  'Cartilages': 'Хрущяли',
  'Cartilages_right': 'Хрущяли_дясно',
  'cerebellum': 'малък мозък',
  'Cerebellum': 'Малък мозък',
  'cerebrum': 'голям мозък',
  'Cerebrum': 'Голям мозък',
  'diencephalon': 'междинен мозък',
  'Diencephalon': 'Междинен мозък',
  'esophagus': 'хранопровод',
  'Esophagus': 'Хранопровод',
  'Esophagus — everything': 'Хранопровод — всичко',
  'Exploded skull — bones': 'Разглобен череп — кости',
  'Exploded skull — whole': 'Разглобен череп — цял',
  'Fascia': 'Фасция',
  'Fibrous skeleton': 'Фиброзен скелет',
  'fibrous skeleton of heart': 'фиброзен скелет на сърцето',
  'Forearm - arteries': 'Предмишница - артерии',
  'Forearm - bones': 'Предмишница - кости',
  'Forearm - capsules, ligaments, fasciae': 'Предмишница - капсули, връзки, фасции',
  'Forearm - cartilages': 'Предмишница - хрущяли',
  'Forearm - muscles': 'Предмишница - мускули',
  'Forearm - nerves': 'Предмишница - нерви',
  'Forearm - synovia, bursae': 'Предмишница - синовия, бурси',
  'Forearm - veins': 'Предмишница - вени',
  'Forearm — all structures': 'Предмишница — всички структури',
  'Forearm — arteries': 'Предмишница — артерии',
  'Forearm — bones': 'Предмишница — кости',
  'Forearm — capsules, ligaments, fasciae': 'Предмишница — капсули, връзки, фасции',
  'Forearm — cartilages': 'Предмишница — хрущяли',
  'Forearm — muscles': 'Предмишница — мускули',
  'Forearm — nerves': 'Предмишница — нерви',
  'Forearm — synovia, bursae': 'Предмишница — синовия, бурси',
  'Forearm — veins': 'Предмишница — вени',
  'gallbladder': 'жлъчен мехур',
  'Gallbladder': 'Жлъчен мехур',
  'Gallbladder — everything': 'Жлъчен мехур — всичко',
  'Hand': 'Ръка',
  'Hand — Arteries': 'Ръка — артерии',
  'Hand — Bones': 'Ръка — кости',
  'Hand — Bursae': 'Ръка — бурси',
  'Hand — Cartilages': 'Ръка — хрущяли',
  'Hand — everything': 'Ръка — всичко',
  'Hand — Fascia': 'Ръка — фасции',
  'Hand — Ligaments': 'Ръка — връзки',
  'Hand — Muscles': 'Ръка — мускули',
  'Hand — Nerves': 'Ръка — нерви',
  'Hand — Overlays': 'Ръка — наслоявания',
  'Hand — Veins': 'Ръка — вени',
  'Hand and wrist - arteries': 'Ръка и китка - артерии',
  'Hand and wrist - bones': 'Ръка и китка - кости',
  'Hand and wrist - capsules, ligaments, fasciae': 'Ръка и китка - капсули, връзки, фасции',
  'Hand and wrist - cartilages': 'Ръка и китка - хрущяли',
  'Hand and wrist - muscles': 'Ръка и китка - мускули',
  'Hand and wrist - nerves': 'Ръка и китка - нерви',
  'Hand and wrist - synovia, bursae': 'Ръка и китка - синовия, бурси',
  'Hand and wrist - veins': 'Ръка и китка - вени',
  'Hand and wrist — all structures': 'Ръка и китка — всички структури',
  'Hand and wrist — arteries': 'Ръка и китка — артерии',
  'Hand and wrist — bones': 'Ръка и китка — кости',
  'Hand and wrist — capsules, ligaments, fasciae': 'Ръка и китка — капсули, връзки, фасции',
  'Hand and wrist — cartilages': 'Ръка и китка — хрущяли',
  'Hand and wrist — muscles': 'Ръка и китка — мускули',
  'Hand and wrist — nerves': 'Ръка и китка — нерви',
  'Hand and wrist — synovia, bursae': 'Ръка и китка — синовия, бурси',
  'Hand and wrist — veins': 'Ръка и китка — вени',
  'Head and neck - arteries': 'Глава и шия - артерии',
  'Head and neck - bones': 'Глава и шия - кости',
  'Head and neck - cartilages': 'Глава и шия - хрущяли',
  'Head and neck - nerves': 'Глава и шия - нерви',
  'Head and neck — all structures': 'Глава и шия — всички структури',
  'Head and neck — arteries': 'Глава и шия — артерии',
  'Head and neck — bones': 'Глава и шия — кости',
  'Head and neck — cartilages': 'Глава и шия — хрущяли',
  'Head and neck — nerves': 'Глава и шия — нерви',
  'Heart — everything': 'Сърце — всичко',
  'Heart (chambers)': 'Сърце (камери)',
  'Kidneys': 'Бъбреци',
  'Kidneys — everything': 'Бъбреци — всичко',
  'large intestine': 'дебело черво',
  'Large intestine': 'Дебело черво',
  'Large intestine — everything': 'Дебело черво — всичко',
  'left adrenal gland': 'лява надбъбречна жлеза',
  'Left adrenal gland': 'Лява надбъбречна жлеза',
  'left atrium': 'ляво предсърдие',
  'Left atrium': 'Ляво предсърдие',
  'left kidney': 'ляв бъбрек',
  'Left kidney': 'Ляв бъбрек',
  'Left lobe': 'Ляв лоб',
  'left lobe of liver': 'ляв лоб на черния дроб',
  'left lobe of thymus': 'ляв дял на тимуса',
  'left lung': 'ляв бял дроб',
  'Left lung': 'Ляв бял дроб',
  'left ventricle': 'лява камера',
  'Left ventricle': 'Лява камера',
  'Ligaments': 'Лигаменти',
  'Liver — everything': 'Черен дроб — всичко',
  'Liver (lobes)': 'Черен дроб (лобове)',
  'Lower limb': 'Долен крайник',
  'Lower limb — Arteries': 'Долен крайник — Артерии',
  'Lower limb — Bones': 'Долен крайник — Кости',
  'Lower limb — Bursae': 'Долен крайник — Бурси',
  'Lower limb — Cartilages': 'Долен крайник — Хрущяли',
  'Lower limb — everything': 'Долен крайник — всичко',
  'Lower limb — Fascia': 'Долен крайник — Фасции',
  'Lower limb — Ligaments': 'Долен крайник — Лигаменти',
  'Lower limb — Muscles': 'Долен крайник — Мускули',
  'Lower limb — Nerves': 'Долен крайник — Нерви',
  'Lower limb — Overlays': 'Долен крайник — Наслагвания',
  'Lower limb — Veins': 'Долен крайник — Вени',
  'Lungs': 'Бели дробове',
  'Lungs — everything': 'Бели дробове — всичко',
  'medulla oblongata': 'продълговат мозък',
  'Medulla oblongata': 'Продълговат мозък',
  'midbrain': 'среден мозък',
  'Midbrain': 'Среден мозък',
  'Muscle attachments — everything': 'Мускулни прикрепвания — всичко',
  'Muscle attachments (insertions & origins)': 'Мускулни прикрепвания (начало и залавно място)',
  'Muscles': 'Мускули',
  'Muscles of abdomen': 'Мускули на корема',
  'Muscles of Abdomen': 'Мускули на корема',
  'Muscles of back': 'Мускули на гърба',
  'Muscles of Back': 'Мускули на гърба',
  'Muscles of head': 'Мускули на главата',
  'Muscles of Head': 'Мускули на главата',
  'Muscles of lower limb': 'Мускули на долния крайник',
  'Muscles of Lower limb': 'Мускули на долния крайник',
  'Muscles of the neck': 'Мускули на шията',
  'Muscles of the Neck': 'Мускули на шията',
  'Muscles of thorax': 'Мускули на гръдния кош',
  'Muscles of Thorax': 'Мускули на гръдния кош',
  'Muscles of thorax, abdomen & back': 'Мускули на гръдния кош, корема и гърба',
  'Muscles of upper limb': 'Мускули на горния крайник',
  'Muscles of Upper limb': 'Мускули на горния крайник',
  'Nerves': 'Нерви',
  'Overlays': 'Наслагвания',
  'pancreas': 'панкреас',
  'Pancreas': 'Панкреас',
  'Pancreas — everything': 'Панкреас — всичко',
  'Pectoral girdle - arteries': 'Пояс на горния крайник - артерии',
  'Pectoral girdle - bones': 'Пояс на горния крайник - кости',
  'Pectoral girdle - capsules, ligaments, fasciae': 'Пояс на горния крайник - капсули, връзки, фасции',
  'Pectoral girdle - cartilages': 'Пояс на горния крайник - хрущяли',
  'Pectoral girdle - muscles': 'Пояс на горния крайник - мускули',
  'Pectoral girdle - nerves': 'Пояс на горния крайник - нерви',
  'Pectoral girdle - synovia, bursae': 'Пояс на горния крайник - синовия, бурси',
  'Pectoral girdle - veins': 'Пояс на горния крайник - вени',
  'Pectoral girdle — all structures': 'Пояс на горния крайник — всички структури',
  'Pectoral girdle — arteries': 'Пояс на горния крайник — артерии',
  'Pectoral girdle — bones': 'Пояс на горния крайник — кости',
  'Pectoral girdle — capsules, ligaments, fasciae': 'Пояс на горния крайник — капсули, връзки, фасции',
  'Pectoral girdle — cartilages': 'Пояс на горния крайник — хрущяли',
  'Pectoral girdle — muscles': 'Пояс на горния крайник — мускули',
  'Pectoral girdle — nerves': 'Пояс на горния крайник — нерви',
  'Pectoral girdle — synovia, bursae': 'Пояс на горния крайник — синовия, бурси',
  'Pectoral girdle — veins': 'Пояс на горния крайник — вени',
  'pons': 'мост',
  'Pons': 'Мост',
  'prostate': 'простата',
  'Prostate': 'Простатна жлеза',
  'Prostate — everything': 'Простатна жлеза — всичко',
  'right adrenal gland': 'дясна надбъбречна жлеза',
  'Right adrenal gland': 'Дясна надбъбречна жлеза',
  'right atrium': 'дясно предсърдие',
  'Right atrium': 'Дясно предсърдие',
  'right kidney': 'десен бъбрек',
  'Right kidney': 'Десен бъбрек',
  'Right lobe': 'Десен дял',
  'right lobe of liver': 'десен дял на черния дроб',
  'right lobe of thymus': 'десен дял на тимуса',
  'right lung': 'десен бял дроб',
  'Right lung': 'Десен бял дроб',
  'right ventricle': 'дясна камера',
  'Right ventricle': 'Дясна камера',
  'Skeleton — appendicular (right) bones': 'Скелет — апендикуларни (десни) кости',
  'Skeleton — axial bones': 'Скелет — аксиални кости',
  'Skeleton — costal cartilages (right)': 'Скелет — ребрени хрущяли (десни)',
  'Skeleton (overview)': 'Скелет (общ преглед)',
  'Skull — median/axial bones': 'Череп — медиални/аксиални кости',
  'Skull — paired (right) bones': 'Череп — сдвоени (десни) кости',
  'Skull — whole': 'Череп — цял',
  'Skull (coloured)': 'Череп (оцветен)',
  'Skull (exploded view)': 'Череп (разглобен изглед)',
  'Skull base — bones': 'Основа на черепа — кости',
  'Skull base — whole': 'Основа на черепа — цяла',
  'Skull base (coloured)': 'Основа на черепа (оцветена)',
  'small intestine': 'тънко черво',
  'Small intestine': 'Тънко черво',
  'Small intestine — everything': 'Тънко черво — всичко',
  'stomach': 'стомах',
  'Stomach': 'Стомах',
  'Stomach — everything': 'Стомах — всичко',
  'Thorax - arteries': 'Торакс - артерии',
  'Thorax - bones': 'Торакс - кости',
  'Thorax - cartilages': 'Торакс - хрущяли',
  'Thorax - nerves': 'Торакс - нерви',
  'Thorax - veins': 'Торакс - вени',
  'Thorax — all structures': 'Торакс — всички структури',
  'Thorax — arteries': 'Торакс — артерии',
  'Thorax — bones': 'Торакс — кости',
  'Thorax — cartilages': 'Торакс — хрущяли',
  'Thorax — nerves': 'Торакс — нерви',
  'Thorax — veins': 'Торакс — вени',
  'Thymus': 'Тимус',
  'Thymus — everything': 'Тимус — всичко',
  'trachea': 'трахея',
  'Trachea': 'Трахея',
  'Trachea — everything': 'Трахея — всичко',
  'Trunk muscles — everything': 'Мускули на туловището — всичко',
  'Typical vertebrae': 'Типични прешлени',
  'Typical vertebrae (C / T / L)': 'Типични прешлени (C / T / L)',
  'Upper limb': 'Горен крайник',
  'Upper limb — everything': 'Горен крайник — всичко',
  'urinary bladder': 'пикочен мехур',
  'Urinary bladder': 'Пикочен мехур',
  'Urinary bladder — everything': 'Пикочен мехур — всичко',
  'Veins': 'Вени',
  'ventricular system': 'вентрикуларна система',
  'Ventricular system': 'Вентрикуларна система',
  'Whole skeleton': 'Цял скелет',

  // Brachial plexus stages (reviewed).
  'Brachial plexus': 'Раменен сплит',
  'Brachial plexus — everything': 'Раменен сплит — всичко',
  'Roots': 'Корени',
  'Trunks': 'Стволове',
  'Divisions': 'Деления',
  'Cords': 'Фасцикули',
  'Branches': 'Клонове',
  '0 Nerves: Roots': 'Корени',
  '1 Nerves: Trunks': 'Стволове',
  '2 Nerves: Divisions': 'Деления',
  '3 Nerves: Cords': 'Фасцикули',
  '4 Nerves: Branches': 'Клонове',
};
