// AUTO-GENERATED by scripts/gen-subject-coverage.mjs (do not edit by hand).
//
// Build-time snapshot of DOCUMENT counts per taxonomy triple. Lets the UI grey
// out subjects with no literature and lets the chat route short-circuit them
// without an LLM call — no page-load DB query.
//
// Keys are the FULL TRIPLE `faculty_id||specialty_id||subject`. Subject names
// are NOT unique across faculties (Клинична лаборатория, Фармакология,
// Патофизиология each appear under several), so never key on the name alone.
//
// Only populated triples are listed — absence means zero.
//
// 74 populated of 396 taxonomy triples; 443 documents.
// Generated 2026-08-03T06:11:35.895Z

export interface CoverageEntry {
  docs: number;
}

/** faculty_id||specialty_id||subject -> document count (populated only). */
export const SUBJECT_COVERAGE: Record<string, CoverageEntry> = {
  "deso||ezikovi||Английски език": { docs: 7 },
  "deso||ezikovi||Български език": { docs: 2 },
  "deso||ezikovi||Латински език с медицински термини": { docs: 9 },
  "deso||ezikovi||Немски език": { docs: 2 },
  "farmacia||farmacia||Аналитична химия": { docs: 2 },
  "farmacia||farmacia||Анатомия и физиология": { docs: 1 },
  "farmacia||farmacia||Биофизика": { docs: 1 },
  "farmacia||farmacia||Биохимия": { docs: 1 },
  "farmacia||farmacia||Неорганична химия": { docs: 2 },
  "farmacia||farmacia||Органична химия": { docs: 2 },
  "farmacia||farmacia||Патофизиология": { docs: 1 },
  "farmacia||farmacia||Фармакогнозия": { docs: 1 },
  "farmacia||farmacia||Фармакология": { docs: 8 },
  "farmacia||farmacia||Фармацевтична ботаника": { docs: 1 },
  "farmacia||farmacia||Фармацевтична химия": { docs: 2 },
  "farmacia||farmacia||Физика": { docs: 1 },
  "farmacia||farmacia||Физикохимия": { docs: 2 },
  "farmacia||farmacia||Хигиена и екология": { docs: 2 },
  "foz||рехабилитация||Фармакология и фармакотерапия": { docs: 1 },
  "foz||kineziterapia||Кинезитерапия при неврологични заболявания": { docs: 1 },
  "foz||kineziterapia||Патофизиология": { docs: 1 },
  "foz||kineziterapia||Спортна медицина": { docs: 1 },
  "foz||kineziterapia||Физикална терапия": { docs: 1 },
  "fvm||veterinarna||Акушерство, репродукция и репродуктивни нарушения": { docs: 2 },
  "fvm||veterinarna||Ветеринарна патоанатомия": { docs: 1 },
  "fvm||veterinarna||Ветеринарна фармакология и токсикология": { docs: 1 },
  "fzg||laborant||Клинична лаборатория": { docs: 5 },
  "fzg||rentgenov||Образна диагностика - обща част": { docs: 1 },
  "fzg||rentgenov||Рентгенова техника": { docs: 1 },
  "fzg||sestra||Акушерство и гинекология": { docs: 2 },
  "fzg||sestra||Анатомия": { docs: 7 },
  "fzg||sestra||Анестезиология и интензивни грижи": { docs: 1 },
  "fzg||sestra||Микробиология": { docs: 2 },
  "fzg||sestra||Социална медицина": { docs: 2 },
  "fzg||sestra||Физиология": { docs: 2 },
  "fzg||sestra||Хирургия": { docs: 1 },
  "medicina||medicina||Акушерство и гинекология": { docs: 8 },
  "medicina||medicina||Анатомия и хистология": { docs: 60 },
  "medicina||medicina||Анестезиология и интензивно лечение": { docs: 5 },
  "medicina||medicina||Биология": { docs: 12 },
  "medicina||medicina||Биофизика": { docs: 3 },
  "medicina||medicina||Биохимия": { docs: 20 },
  "medicina||medicina||Дерматология и венерология": { docs: 3 },
  "medicina||medicina||Кардиология": { docs: 1 },
  "medicina||medicina||Клинична алергология": { docs: 3 },
  "medicina||medicina||Клинична лаборатория": { docs: 5 },
  "medicina||medicina||Клинична токсикология": { docs: 1 },
  "medicina||medicina||Медицина на бедствените ситуации": { docs: 2 },
  "medicina||medicina||Медицинска генетика": { docs: 7 },
  "medicina||medicina||Медицинска психология": { docs: 3 },
  "medicina||medicina||Микробиология": { docs: 20 },
  "medicina||medicina||Неврохирургия": { docs: 5 },
  "medicina||medicina||Нервни болести": { docs: 10 },
  "medicina||medicina||Обща и оперативна хирургия": { docs: 4 },
  "medicina||medicina||Обща медицина": { docs: 1 },
  "medicina||medicina||Онкология": { docs: 2 },
  "medicina||medicina||Ортопедия и травматология": { docs: 7 },
  "medicina||medicina||Очни болести": { docs: 5 },
  "medicina||medicina||Патоанатомия и цитопатология": { docs: 15 },
  "medicina||medicina||Патофизиология": { docs: 6 },
  "medicina||medicina||Пропедевтика на вътрешните болести": { docs: 3 },
  "medicina||medicina||Рентгенология и радиология": { docs: 2 },
  "medicina||medicina||Спешна медицина": { docs: 4 },
  "medicina||medicina||Урология": { docs: 6 },
  "medicina||medicina||Ушни, носни и гърлени болести": { docs: 7 },
  "medicina||medicina||Фармакология": { docs: 21 },
  "medicina||medicina||Фармакология с клинична фармакология": { docs: 9 },
  "medicina||medicina||Физика": { docs: 6 },
  "medicina||medicina||Физиология": { docs: 21 },
  "medicina||medicina||Физиотерапия и рехабилитация": { docs: 5 },
  "medicina||medicina||Хигиена, екология и професионални заболявания": { docs: 18 },
  "medicina||medicina||Химия": { docs: 39 },
  "medicina||medicina||Хирургически болести": { docs: 5 },
  "medicina||medicina||Цитология": { docs: 9 },
};

/** faculty_id -> document count across all its subjects. */
export const FACULTY_COVERAGE: Record<string, number> = {
  "deso": 20,
  "farmacia": 27,
  "foz": 5,
  "fvm": 4,
  "fzg": 24,
  "medicina": 363,
};

/** faculty_id||specialty_id -> document count across all its subjects. */
export const SPECIALTY_COVERAGE: Record<string, number> = {
  "deso||ezikovi": 20,
  "farmacia||farmacia": 27,
  "foz||рехабилитация": 1,
  "foz||kineziterapia": 4,
  "fvm||veterinarna": 4,
  "fzg||laborant": 5,
  "fzg||rentgenov": 2,
  "fzg||sestra": 17,
  "medicina||medicina": 363,
};

export const COVERAGE_META = {
  "generatedAt": "2026-08-03T06:11:35.895Z",
  "taxonomyCount": 396,
  "populatedTriples": 74,
  "totalDocuments": 443,
  "excludedDocuments": 1
} as const;

/** Build the canonical coverage key. Always use this — never hand-concatenate. */
export function coverageKey(facultyId: string, specialtyId: string, subject: string): string {
  return facultyId + '||' + specialtyId + '||' + subject;
}

/** Documents for a full triple. 0 when the subject has no literature. */
export function docsForSubject(facultyId: string, specialtyId: string, subject: string): number {
  return SUBJECT_COVERAGE[coverageKey(facultyId, specialtyId, subject)]?.docs ?? 0;
}

/** Documents across a whole faculty. */
export function docsForFaculty(facultyId: string): number {
  return FACULTY_COVERAGE[facultyId] ?? 0;
}

/** Documents across a whole specialty. */
export function docsForSpecialty(facultyId: string, specialtyId: string): number {
  return SPECIALTY_COVERAGE[facultyId + '||' + specialtyId] ?? 0;
}

/** Bulgarian document-count badge: 1 документ / N документа. */
export function docsLabel(docs: number): string {
  return docs === 1 ? '1 документ' : docs + ' документа';
}
